var fs = require('fs');
var path = require('path');

// Replace with your unique name
exports.appName = 'LoopBackPushNotificationDemoApplication';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'AAAAS4ceBkE:APA91bFScAqrSc9hS6xVpPsaKVopmEQu7gmcW7gj0V2rcIC5bQEhqK4VyMLOTQbJS40GO196AzdgH2_z1EYR_pYSk9gTWLT5HEgpKS5Jss6wWaoFWz9-1PcDC0_eve2YLoPmxupFyWNW';

// You may want to use your own credentials here
//exports.apnsCertData = readCredentialsFile('apns_cert_dev.pem');
//exports.apnsKeyData =readCredentialsFile('apns_key_dev.pem');


//--- Helper functions ---

function readCredentialsFile(name) {
  return fs.readFileSync(
    path.resolve(__dirname, 'credentials', name),
    'UTF-8'
  );
}